### ISSUE TITLE
To add redirect_url to linkedIn and origin to google authorization

### ISSUE THREAD

**Issue by vitalik77795** [CarSnoop-Inc/carsnoop-issues#218]
Hello @billypilgrim88 . We've faced an issue on with google and linkedIn authorization on new stands:
https://shop.carsnoop.com/
https://shop-dev.carsnoop.com/
https://shop-test.carsnoop.com/
In case of google authorization process the error is `[GSI_LOGGER]: The given origin is not allowed for the given client ID.` And as far as I've understood we need to add the site domains to the Authorised JavaScript origins.
In case of linkedin authorization the error is `The redirect_uri does not match the registered value` and we need to add domains to Authorized redirect URL's list.
So, could you add domains to google and linkedIn settings or give me an access to these platforms and I will add them.

**Comment by billypilgrim88** [comment]
Fixed, can you try again and close the issue if everything looks good?

**Comment by vitalik77795** [comment]
Thanks. For google everything looks great. But for linkedIn still have a problem `The redirect_uri does not match the registered value`. So, could you, please, check the list of redirect urls one more time.

**Comment by billypilgrim88** [comment]
Fixed.

**Comment by billypilgrim88** [comment]
Fixed.

**Comment by vitalik77795** [comment]
Fixed
